// <auto-generated />
namespace MvcCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mg05 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mg05));
        
        string IMigrationMetadata.Id
        {
            get { return "202012250906082_mg05"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
