// <auto-generated />
namespace MvcCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Arif20 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Arif20));
        
        string IMigrationMetadata.Id
        {
            get { return "202012271341536_Arif20"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
